export enum ResidenceType {
  TENANT = 'Tenant',
  OCCUPANT = 'Occupant',
}

export enum RoommateRequestStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum MyStaysDocumentType {
  LEAVE_NOTICE = 'LEAVE_NOTICE',
  WATER_TRANSFER = 'WATER_TRANSFER',
  ELECTRICITY = 'ELECTRICITY',
  GAS_TRANSFER = 'GAS_TRANSFER',
  HOT_WATER_TANK = 'HOT_WATER_TANK',
  TENANT_INSURANCE = 'TENANT_INSURANCE',
  LEASE_AGREEMENT = 'LEASE_AGREEMENT',
  OFFER_TO_LEASE = 'OFFER_TO_LEASE',
}
